spring:
  security:
    basic:
      enable: true
    user:
      name: admin
      password: admin123
  #http:
    #multipart:
      #maxRequestSize: 800Mb
  servlet:
    multipart:
      maxFileSize: 800MB
      maxRequestSize: 800MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${databaseUrl}
    username: ${databaseUsername}
    password: ${databasePassword}
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
    host: 192.168.1.113
    port: 6379
    timeout: 3600
    cluster:
      nodes: ${redisUrl}
    password: ${redisPassword}
    pool:
      max:
        active: 10
        idle: 8
        wait: -1
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql
  reasonable: false
feign:
  hystrix:
    enabled: false
  httpclient:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
  ConnectTimeout: 6000
  ReadTimeout: 6000
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 2
  MaxAutoRetries: 1
mybatis:
  mapper-locations: classpath:top/quhailong/pan/file/dao/mapping/*.xml
  type-aliases-package: top.quhailong.pan.file.entity
management:
  endpoints:
    web:
      #Actuator 默认所有的监控点路径都在/actuator/*，当然如果有需要这个路径也支持定制。
      base-path: /monitor
      #Actuator 默认只开放了两个端点 /actuator/health 和 /actuator/info
      exposure:
        #打开所有的监控点
        include: '*'
        #屏蔽env,beans监控点
        exclude: env,beans
  endpoint:
    health:
      #详细显示health信息
      show-details: always
      #启用接口关闭 Spring Boot (post请求)
      shutdown:
        enabled: true
  health:
    defaults:
      enabled: true
