server: 
  port: 8095
  
spring: 
  application: 
    name: core-zuul
  servlet:
    multipart:
      maxFileSize: 800MB
      maxRequestSize: 800MB
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.93.128:8848
        password: nacos
        username: nacos

management:
  endpoints:
    web:
      #Actuator 默认所有的监控点路径都在/actuator/*，当然如果有需要这个路径也支持定制。
      base-path: /monitor
      #Actuator 默认只开放了两个端点 /actuator/health 和 /actuator/info
      exposure:
        #打开所有的监控点
        include: '*'
        #屏蔽env,beans监控点
        exclude: env,beans
  endpoint:
    health:
      #详细显示health信息
      show-details: always
      #启用接口关闭 Spring Boot (post请求)
      shutdown:
        enabled: true
  health:
    defaults:
      enabled: true

    
ribbon: 
  ReadTimeout: 60000
  ConnectTimeout: 60000
  
zuul: 
  sensitiveHeaders:
  routes:
    core:
      path: /api/core/**
      serviceId: core-service
    edge:
      path: /api/edge/**
      serviceId: edge-service
    user:
      path: /api/user/**
      serviceId: user-service
    share:
      path: /api/share/**
      serviceId: share-service